// Default deck metadata for bundled decks
// These are used as fallback when no database decks exist

export interface DefaultDeck {
  id: string
  title: string
  images: string[]
  cards_count: number
  is_public: boolean
  plays: number
  user: null
  isFavorited: boolean
  likes: number
  isOwned: boolean
}

export const DEFAULT_DECKS: DefaultDeck[] = [
  // 16-card decks (8 pairs)
  {
    id: "default-classic-animals-16",
    title: "Classic Animals",
    images: [
      "/cute-cat.png",
      "/happy-golden-retriever.png",
      "/majestic-african-elephant.png",
      "/lion.jpg",
      "/solitary-penguin.png",
      "/butterfly.png",
      "/fluffy-brown-rabbit.png",
      "/majestic-owl.png",
    ],
    cards_count: 16,
    is_public: true,
    plays: 1247,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },
  {
    id: "default-space-adventure-16",
    title: "Space Adventure",
    images: [
      "/rocket-ship.jpg",
      "/planet-earth.png",
      "/astronaut-contemplating.png",
      "/full-moon-night.png",
      "/night-sky-stars.png",
      "/earth-orbiting-satellite.png",
      "/otherworldly-visitor.png",
      "/futuristic-space-station.png",
    ],
    cards_count: 16,
    is_public: true,
    plays: 892,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },
  {
    id: "default-ocean-life-16",
    title: "Ocean Life",
    images: [
      "/playful-dolphin.png",
      "/whimsical-seahorse.png",
      "/starfish.jpg",
      "/majestic-whale.png",
      "/octopus.jpg",
      "/vibrant-coral-reef.png",
      "/serene-sea-turtle.png",
      "/glowing-jellyfish.png",
    ],
    cards_count: 16,
    is_public: true,
    plays: 634,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },

  // 24-card decks (12 pairs)
  {
    id: "default-classic-animals-extended-24",
    title: "Classic Animals Extended",
    images: [
      "/cute-cat.png",
      "/happy-golden-retriever.png",
      "/majestic-african-elephant.png",
      "/lion.jpg",
      "/solitary-penguin.png",
      "/butterfly.png",
      "/fluffy-brown-rabbit.png",
      "/majestic-owl.png",
      "/playful-dolphin.png",
      "/whimsical-seahorse.png",
      "/starfish.jpg",
      "/majestic-whale.png",
    ],
    cards_count: 24,
    is_public: true,
    plays: 856,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },
  {
    id: "default-space-adventure-extended-24",
    title: "Space Adventure Extended",
    images: [
      "/rocket-ship.jpg",
      "/planet-earth.png",
      "/astronaut-contemplating.png",
      "/full-moon-night.png",
      "/night-sky-stars.png",
      "/earth-orbiting-satellite.png",
      "/otherworldly-visitor.png",
      "/futuristic-space-station.png",
      "/vibrant-coral-reef.png",
      "/serene-sea-turtle.png",
      "/glowing-jellyfish.png",
      "/octopus.jpg",
    ],
    cards_count: 24,
    is_public: true,
    plays: 723,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },
  {
    id: "default-ocean-life-extended-24",
    title: "Ocean Life Extended",
    images: [
      "/playful-dolphin.png",
      "/whimsical-seahorse.png",
      "/starfish.jpg",
      "/majestic-whale.png",
      "/octopus.jpg",
      "/vibrant-coral-reef.png",
      "/serene-sea-turtle.png",
      "/glowing-jellyfish.png",
      "/cute-cat.png",
      "/happy-golden-retriever.png",
      "/majestic-african-elephant.png",
      "/lion.jpg",
    ],
    cards_count: 24,
    is_public: true,
    plays: 612,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },

  // 32-card decks (16 pairs)
  {
    id: "default-ultimate-animals-32",
    title: "Ultimate Animals Collection",
    images: [
      "/cute-cat.png",
      "/happy-golden-retriever.png",
      "/majestic-african-elephant.png",
      "/lion.jpg",
      "/solitary-penguin.png",
      "/butterfly.png",
      "/fluffy-brown-rabbit.png",
      "/majestic-owl.png",
      "/playful-dolphin.png",
      "/whimsical-seahorse.png",
      "/starfish.jpg",
      "/majestic-whale.png",
      "/octopus.jpg",
      "/vibrant-coral-reef.png",
      "/serene-sea-turtle.png",
      "/glowing-jellyfish.png",
    ],
    cards_count: 32,
    is_public: true,
    plays: 445,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },
  {
    id: "default-ultimate-space-32",
    title: "Ultimate Space Collection",
    images: [
      "/rocket-ship.jpg",
      "/planet-earth.png",
      "/astronaut-contemplating.png",
      "/full-moon-night.png",
      "/night-sky-stars.png",
      "/earth-orbiting-satellite.png",
      "/otherworldly-visitor.png",
      "/futuristic-space-station.png",
      "/cute-cat.png",
      "/happy-golden-retriever.png",
      "/majestic-african-elephant.png",
      "/lion.jpg",
      "/playful-dolphin.png",
      "/whimsical-seahorse.png",
      "/starfish.jpg",
      "/majestic-whale.png",
    ],
    cards_count: 32,
    is_public: true,
    plays: 387,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },
  {
    id: "default-ultimate-ocean-32",
    title: "Ultimate Ocean Collection",
    images: [
      "/playful-dolphin.png",
      "/whimsical-seahorse.png",
      "/starfish.jpg",
      "/majestic-whale.png",
      "/octopus.jpg",
      "/vibrant-coral-reef.png",
      "/serene-sea-turtle.png",
      "/glowing-jellyfish.png",
      "/rocket-ship.jpg",
      "/planet-earth.png",
      "/astronaut-contemplating.png",
      "/full-moon-night.png",
      "/night-sky-stars.png",
      "/earth-orbiting-satellite.png",
      "/otherworldly-visitor.png",
      "/futuristic-space-station.png",
    ],
    cards_count: 32,
    is_public: true,
    plays: 298,
    user: null,
    isFavorited: false,
    likes: 0,
    isOwned: false,
  },
]
